// Fichier généré par scripts/generer-villes.mjs (geo.api.gouv.fr) — ne pas modifier à la main
import type { Carte } from "./cartes";

export const CARTES_VILLES: Carte[] = [
  {
    "id": 90047001,
    "nom": "Agen",
    "emoji": "🏙️",
    "description": "32 801 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Lot-et-Garonne",
    "sigle": "47",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013001,
    "nom": "Aix-en-Provence",
    "emoji": "🏙️",
    "description": "149 695 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90073008,
    "nom": "Aix-les-Bains",
    "emoji": "🏙️",
    "description": "32 406 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Savoie",
    "sigle": "73",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90200004,
    "nom": "Ajaccio",
    "emoji": "🏙️",
    "description": "76 320 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Corse",
    "poste": "Corse-du-Sud",
    "sigle": "2A",
    "couleur": "#374151",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90081004,
    "nom": "Albi",
    "emoji": "🏙️",
    "description": "51 290 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Tarn",
    "sigle": "81",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90030007,
    "nom": "Alès",
    "emoji": "🏙️",
    "description": "46 125 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Gard",
    "sigle": "30",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094002,
    "nom": "Alfortville",
    "emoji": "🏙️",
    "description": "45 531 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90080021,
    "nom": "Amiens",
    "emoji": "🏙️",
    "description": "136 449 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Somme",
    "sigle": "80",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90049007,
    "nom": "Angers",
    "emoji": "🏙️",
    "description": "159 022 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Maine-et-Loire",
    "sigle": "49",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90064024,
    "nom": "Anglet",
    "emoji": "🏙️",
    "description": "43 271 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Pyrénées-Atlantiques",
    "sigle": "64",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90016015,
    "nom": "Angoulême",
    "emoji": "🏙️",
    "description": "41 908 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Charente",
    "sigle": "16",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90074010,
    "nom": "Annecy",
    "emoji": "🏙️",
    "description": "132 117 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Haute-Savoie",
    "sigle": "74",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90074012,
    "nom": "Annemasse",
    "emoji": "🏙️",
    "description": "37 628 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Haute-Savoie",
    "sigle": "74",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90006004,
    "nom": "Antibes",
    "emoji": "🏙️",
    "description": "77 637 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Alpes-Maritimes",
    "sigle": "06",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092002,
    "nom": "Antony",
    "emoji": "🏙️",
    "description": "64 263 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095018,
    "nom": "Argenteuil",
    "emoji": "🏙️",
    "description": "106 130 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013004,
    "nom": "Arles",
    "emoji": "🏙️",
    "description": "51 811 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90062041,
    "nom": "Arras",
    "emoji": "🏙️",
    "description": "42 875 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Pas-de-Calais",
    "sigle": "62",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092004,
    "nom": "Asnières-sur-Seine",
    "emoji": "🏙️",
    "description": "93 941 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091027,
    "nom": "Athis-Mons",
    "emoji": "🏙️",
    "description": "36 613 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013005,
    "nom": "Aubagne",
    "emoji": "🏙️",
    "description": "47 529 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093001,
    "nom": "Aubervilliers",
    "emoji": "🏙️",
    "description": "88 365 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093005,
    "nom": "Aulnay-sous-Bois",
    "emoji": "🏙️",
    "description": "87 599 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90089024,
    "nom": "Auxerre",
    "emoji": "🏙️",
    "description": "35 097 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Bourgogne-Franche-Comté",
    "poste": "Yonne",
    "sigle": "89",
    "couleur": "#6b21a8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90084007,
    "nom": "Avignon",
    "emoji": "🏙️",
    "description": "92 188 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Vaucluse",
    "sigle": "84",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092007,
    "nom": "Bagneux",
    "emoji": "🏙️",
    "description": "44 572 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093006,
    "nom": "Bagnolet",
    "emoji": "🏙️",
    "description": "43 086 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097103,
    "nom": "Baie-Mahault",
    "emoji": "🏙️",
    "description": "30 924 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Guadeloupe",
    "poste": "Guadeloupe",
    "sigle": "971",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90210033,
    "nom": "Bastia",
    "emoji": "🏙️",
    "description": "46 867 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Corse",
    "poste": "Haute-Corse",
    "sigle": "2B",
    "couleur": "#374151",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90064102,
    "nom": "Bayonne",
    "emoji": "🏙️",
    "description": "54 306 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Pyrénées-Atlantiques",
    "sigle": "64",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90060057,
    "nom": "Beauvais",
    "emoji": "🏙️",
    "description": "55 550 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Oise",
    "sigle": "60",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90033039,
    "nom": "Bègles",
    "emoji": "🏙️",
    "description": "31 831 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Gironde",
    "sigle": "33",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90090010,
    "nom": "Belfort",
    "emoji": "🏙️",
    "description": "45 912 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Bourgogne-Franche-Comté",
    "poste": "Territoire de Belfort",
    "sigle": "90",
    "couleur": "#6b21a8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90025056,
    "nom": "Besançon",
    "emoji": "🏙️",
    "description": "118 489 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Bourgogne-Franche-Comté",
    "poste": "Doubs",
    "sigle": "25",
    "couleur": "#6b21a8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90034032,
    "nom": "Béziers",
    "emoji": "🏙️",
    "description": "81 545 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Hérault",
    "sigle": "34",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095063,
    "nom": "Bezons",
    "emoji": "🏙️",
    "description": "36 434 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90041018,
    "nom": "Blois",
    "emoji": "🏙️",
    "description": "47 219 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Centre-Val de Loire",
    "poste": "Loir-et-Cher",
    "sigle": "41",
    "couleur": "#0f766e",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093008,
    "nom": "Bobigny",
    "emoji": "🏙️",
    "description": "56 927 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093010,
    "nom": "Bondy",
    "emoji": "🏙️",
    "description": "50 595 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90033063,
    "nom": "Bordeaux",
    "emoji": "🏙️",
    "description": "267 991 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Gironde",
    "sigle": "33",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092012,
    "nom": "Boulogne-Billancourt",
    "emoji": "🏙️",
    "description": "119 019 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90062160,
    "nom": "Boulogne-sur-Mer",
    "emoji": "🏙️",
    "description": "40 539 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Pas-de-Calais",
    "sigle": "62",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90001053,
    "nom": "Bourg-en-Bresse",
    "emoji": "🏙️",
    "description": "42 372 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Ain",
    "sigle": "01",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90018033,
    "nom": "Bourges",
    "emoji": "🏙️",
    "description": "64 186 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Centre-Val de Loire",
    "poste": "Cher",
    "sigle": "18",
    "couleur": "#0f766e",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90038053,
    "nom": "Bourgoin-Jallieu",
    "emoji": "🏙️",
    "description": "30 151 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Isère",
    "sigle": "38",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90029019,
    "nom": "Brest",
    "emoji": "🏙️",
    "description": "142 346 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Bretagne",
    "poste": "Finistère",
    "sigle": "29",
    "couleur": "#111827",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90019031,
    "nom": "Brive-la-Gaillarde",
    "emoji": "🏙️",
    "description": "47 095 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Corrèze",
    "sigle": "19",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069029,
    "nom": "Bron",
    "emoji": "🏙️",
    "description": "42 982 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094016,
    "nom": "Cachan",
    "emoji": "🏙️",
    "description": "31 103 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90014118,
    "nom": "Caen",
    "emoji": "🏙️",
    "description": "109 400 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Normandie",
    "poste": "Calvados",
    "sigle": "14",
    "couleur": "#991b1b",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90006027,
    "nom": "Cagnes-sur-Mer",
    "emoji": "🏙️",
    "description": "53 354 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Alpes-Maritimes",
    "sigle": "06",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90062193,
    "nom": "Calais",
    "emoji": "🏙️",
    "description": "67 571 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Pas-de-Calais",
    "sigle": "62",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069034,
    "nom": "Caluire-et-Cuire",
    "emoji": "🏙️",
    "description": "43 597 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059122,
    "nom": "Cambrai",
    "emoji": "🏙️",
    "description": "31 134 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90006029,
    "nom": "Cannes",
    "emoji": "🏙️",
    "description": "74 350 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Alpes-Maritimes",
    "sigle": "06",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90011069,
    "nom": "Carcassonne",
    "emoji": "🏙️",
    "description": "46 080 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Aude",
    "sigle": "11",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90084031,
    "nom": "Carpentras",
    "emoji": "🏙️",
    "description": "31 619 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Vaucluse",
    "sigle": "84",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90081065,
    "nom": "Castres",
    "emoji": "🏙️",
    "description": "42 505 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Tarn",
    "sigle": "81",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097302,
    "nom": "Cayenne",
    "emoji": "🏙️",
    "description": "62 675 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Guyane",
    "poste": "Guyane",
    "sigle": "973",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095127,
    "nom": "Cergy",
    "emoji": "🏙️",
    "description": "70 906 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90071076,
    "nom": "Chalon-sur-Saône",
    "emoji": "🏙️",
    "description": "45 102 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Bourgogne-Franche-Comté",
    "poste": "Saône-et-Loire",
    "sigle": "71",
    "couleur": "#6b21a8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90051108,
    "nom": "Châlons-en-Champagne",
    "emoji": "🏙️",
    "description": "42 971 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Marne",
    "sigle": "51",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90073065,
    "nom": "Chambéry",
    "emoji": "🏙️",
    "description": "59 964 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Savoie",
    "sigle": "73",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094017,
    "nom": "Champigny-sur-Marne",
    "emoji": "🏙️",
    "description": "78 072 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90008105,
    "nom": "Charleville-Mézières",
    "emoji": "🏙️",
    "description": "45 560 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Ardennes",
    "sigle": "08",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90028085,
    "nom": "Chartres",
    "emoji": "🏙️",
    "description": "38 324 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Centre-Val de Loire",
    "poste": "Eure-et-Loir",
    "sigle": "28",
    "couleur": "#0f766e",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90036044,
    "nom": "Châteauroux",
    "emoji": "🏙️",
    "description": "42 963 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Centre-Val de Loire",
    "poste": "Indre",
    "sigle": "36",
    "couleur": "#0f766e",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90086066,
    "nom": "Châtellerault",
    "emoji": "🏙️",
    "description": "31 003 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Vienne",
    "sigle": "86",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092019,
    "nom": "Châtenay-Malabry",
    "emoji": "🏙️",
    "description": "35 825 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092020,
    "nom": "Châtillon",
    "emoji": "🏙️",
    "description": "36 705 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078146,
    "nom": "Chatou",
    "emoji": "🏙️",
    "description": "30 598 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90077108,
    "nom": "Chelles",
    "emoji": "🏙️",
    "description": "54 620 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-et-Marne",
    "sigle": "77",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90050129,
    "nom": "Cherbourg-en-Cotentin",
    "emoji": "🏙️",
    "description": "78 258 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Normandie",
    "poste": "Manche",
    "sigle": "50",
    "couleur": "#991b1b",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094022,
    "nom": "Choisy-le-Roi",
    "emoji": "🏙️",
    "description": "45 946 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90049099,
    "nom": "Cholet",
    "emoji": "🏙️",
    "description": "54 404 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Maine-et-Loire",
    "sigle": "49",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092023,
    "nom": "Clamart",
    "emoji": "🏙️",
    "description": "58 576 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90063113,
    "nom": "Clermont-Ferrand",
    "emoji": "🏙️",
    "description": "146 351 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Puy-de-Dôme",
    "sigle": "63",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092024,
    "nom": "Clichy",
    "emoji": "🏙️",
    "description": "64 410 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90068066,
    "nom": "Colmar",
    "emoji": "🏙️",
    "description": "66 970 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Haut-Rhin",
    "sigle": "68",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092025,
    "nom": "Colombes",
    "emoji": "🏙️",
    "description": "91 053 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90031149,
    "nom": "Colomiers",
    "emoji": "🏙️",
    "description": "40 882 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Haute-Garonne",
    "sigle": "31",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90060159,
    "nom": "Compiègne",
    "emoji": "🏙️",
    "description": "40 761 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Oise",
    "sigle": "60",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078172,
    "nom": "Conflans-Sainte-Honorine",
    "emoji": "🏙️",
    "description": "36 958 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091174,
    "nom": "Corbeil-Essonnes",
    "emoji": "🏙️",
    "description": "54 471 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092026,
    "nom": "Courbevoie",
    "emoji": "🏙️",
    "description": "82 902 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90060175,
    "nom": "Creil",
    "emoji": "🏙️",
    "description": "36 301 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Oise",
    "sigle": "60",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094028,
    "nom": "Créteil",
    "emoji": "🏙️",
    "description": "93 397 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90021231,
    "nom": "Dijon",
    "emoji": "🏙️",
    "description": "161 830 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Bourgogne-Franche-Comté",
    "poste": "Côte-d'Or",
    "sigle": "21",
    "couleur": "#6b21a8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059178,
    "nom": "Douai",
    "emoji": "🏙️",
    "description": "40 250 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90083050,
    "nom": "Draguignan",
    "emoji": "🏙️",
    "description": "40 826 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Var",
    "sigle": "83",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093029,
    "nom": "Drancy",
    "emoji": "🏙️",
    "description": "72 390 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091201,
    "nom": "Draveil",
    "emoji": "🏙️",
    "description": "30 098 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90028134,
    "nom": "Dreux",
    "emoji": "🏙️",
    "description": "31 543 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Centre-Val de Loire",
    "poste": "Eure-et-Loir",
    "sigle": "28",
    "couleur": "#0f766e",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90098805,
    "nom": "Dumbéa",
    "emoji": "🏙️",
    "description": "34 926 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Calédonie",
    "poste": "Nouvelle-Calédonie",
    "sigle": "988",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059183,
    "nom": "Dunkerque",
    "emoji": "🏙️",
    "description": "86 263 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90038151,
    "nom": "Échirolles",
    "emoji": "🏙️",
    "description": "37 491 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Isère",
    "sigle": "38",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90088160,
    "nom": "Épinal",
    "emoji": "🏙️",
    "description": "32 251 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Vosges",
    "sigle": "88",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093031,
    "nom": "Épinay-sur-Seine",
    "emoji": "🏙️",
    "description": "52 833 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90027229,
    "nom": "Évreux",
    "emoji": "🏙️",
    "description": "49 360 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Normandie",
    "poste": "Eure",
    "sigle": "27",
    "couleur": "#991b1b",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091228,
    "nom": "Évry-Courcouronnes",
    "emoji": "🏙️",
    "description": "66 919 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094033,
    "nom": "Fontenay-sous-Bois",
    "emoji": "🏙️",
    "description": "53 757 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097209,
    "nom": "Fort-de-France",
    "emoji": "🏙️",
    "description": "75 506 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Martinique",
    "poste": "Martinique",
    "sigle": "972",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095252,
    "nom": "Franconville",
    "emoji": "🏙️",
    "description": "37 754 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90083061,
    "nom": "Fréjus",
    "emoji": "🏙️",
    "description": "59 719 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Var",
    "sigle": "83",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093032,
    "nom": "Gagny",
    "emoji": "🏙️",
    "description": "42 313 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90005061,
    "nom": "Gap",
    "emoji": "🏙️",
    "description": "41 293 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Hautes-Alpes",
    "sigle": "05",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095268,
    "nom": "Garges-lès-Gonesse",
    "emoji": "🏙️",
    "description": "41 791 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092036,
    "nom": "Gennevilliers",
    "emoji": "🏙️",
    "description": "50 979 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095280,
    "nom": "Goussainville",
    "emoji": "🏙️",
    "description": "31 301 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90006069,
    "nom": "Grasse",
    "emoji": "🏙️",
    "description": "50 970 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Alpes-Maritimes",
    "sigle": "06",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90038185,
    "nom": "Grenoble",
    "emoji": "🏙️",
    "description": "156 140 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Isère",
    "sigle": "38",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90067180,
    "nom": "Haguenau",
    "emoji": "🏙️",
    "description": "36 391 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Bas-Rhin",
    "sigle": "67",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095306,
    "nom": "Herblay-sur-Seine",
    "emoji": "🏙️",
    "description": "31 779 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078311,
    "nom": "Houilles",
    "emoji": "🏙️",
    "description": "33 983 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90083069,
    "nom": "Hyères",
    "emoji": "🏙️",
    "description": "55 858 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Var",
    "sigle": "83",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092040,
    "nom": "Issy-les-Moulineaux",
    "emoji": "🏙️",
    "description": "67 669 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013047,
    "nom": "Istres",
    "emoji": "🏙️",
    "description": "44 292 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094041,
    "nom": "Ivry-sur-Seine",
    "emoji": "🏙️",
    "description": "65 064 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90037122,
    "nom": "Joué-lès-Tours",
    "emoji": "🏙️",
    "description": "38 423 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Centre-Val de Loire",
    "poste": "Indre-et-Loire",
    "sigle": "37",
    "couleur": "#0f766e",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097610,
    "nom": "Koungou",
    "emoji": "🏙️",
    "description": "32 156 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Mayotte",
    "poste": "Mayotte",
    "sigle": "976",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094038,
    "nom": "L'Haÿ-les-Roses",
    "emoji": "🏙️",
    "description": "31 188 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013028,
    "nom": "La Ciotat",
    "emoji": "🏙️",
    "description": "38 477 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093027,
    "nom": "La Courneuve",
    "emoji": "🏙️",
    "description": "47 167 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092035,
    "nom": "La Garenne-Colombes",
    "emoji": "🏙️",
    "description": "30 197 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097408,
    "nom": "La Possession",
    "emoji": "🏙️",
    "description": "36 568 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90085191,
    "nom": "La Roche-sur-Yon",
    "emoji": "🏙️",
    "description": "54 849 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Vendée",
    "sigle": "85",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90017300,
    "nom": "La Rochelle",
    "emoji": "🏙️",
    "description": "79 851 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Charente-Maritime",
    "sigle": "17",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90083126,
    "nom": "La Seyne-sur-Mer",
    "emoji": "🏙️",
    "description": "63 732 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Var",
    "sigle": "83",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90053130,
    "nom": "Laval",
    "emoji": "🏙️",
    "description": "49 400 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Mayenne",
    "sigle": "53",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093007,
    "nom": "Le Blanc-Mesnil",
    "emoji": "🏙️",
    "description": "62 376 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90006030,
    "nom": "Le Cannet",
    "emoji": "🏙️",
    "description": "41 938 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Alpes-Maritimes",
    "sigle": "06",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078158,
    "nom": "Le Chesnay-Rocquencourt",
    "emoji": "🏙️",
    "description": "30 689 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90076351,
    "nom": "Le Havre",
    "emoji": "🏙️",
    "description": "166 687 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Normandie",
    "poste": "Seine-Maritime",
    "sigle": "76",
    "couleur": "#991b1b",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097213,
    "nom": "Le Lamentin",
    "emoji": "🏙️",
    "description": "39 400 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Martinique",
    "poste": "Martinique",
    "sigle": "972",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90072181,
    "nom": "Le Mans",
    "emoji": "🏙️",
    "description": "146 249 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Sarthe",
    "sigle": "72",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094058,
    "nom": "Le Perreux-sur-Marne",
    "emoji": "🏙️",
    "description": "35 260 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097407,
    "nom": "Le Port",
    "emoji": "🏙️",
    "description": "33 969 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097422,
    "nom": "Le Tampon",
    "emoji": "🏙️",
    "description": "82 579 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90062498,
    "nom": "Lens",
    "emoji": "🏙️",
    "description": "32 920 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Pas-de-Calais",
    "sigle": "62",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097101,
    "nom": "Les Abymes",
    "emoji": "🏙️",
    "description": "51 055 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Guadeloupe",
    "poste": "Guadeloupe",
    "sigle": "971",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078440,
    "nom": "Les Mureaux",
    "emoji": "🏙️",
    "description": "34 632 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90085194,
    "nom": "Les Sables-d'Olonne",
    "emoji": "🏙️",
    "description": "49 603 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Vendée",
    "sigle": "85",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092044,
    "nom": "Levallois-Perret",
    "emoji": "🏙️",
    "description": "68 092 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90062510,
    "nom": "Liévin",
    "emoji": "🏙️",
    "description": "30 063 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Pas-de-Calais",
    "sigle": "62",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059350,
    "nom": "Lille",
    "emoji": "🏙️",
    "description": "238 246 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90087085,
    "nom": "Limoges",
    "emoji": "🏙️",
    "description": "129 937 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Haute-Vienne",
    "sigle": "87",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093046,
    "nom": "Livry-Gargan",
    "emoji": "🏙️",
    "description": "47 228 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90056121,
    "nom": "Lorient",
    "emoji": "🏙️",
    "description": "58 329 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Bretagne",
    "poste": "Morbihan",
    "sigle": "56",
    "couleur": "#111827",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069123,
    "nom": "Lyon",
    "emoji": "🏙️",
    "description": "519 127 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90071270,
    "nom": "Mâcon",
    "emoji": "🏙️",
    "description": "35 177 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Bourgogne-Franche-Comté",
    "poste": "Saône-et-Loire",
    "sigle": "71",
    "couleur": "#6b21a8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094046,
    "nom": "Maisons-Alfort",
    "emoji": "🏙️",
    "description": "56 799 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092046,
    "nom": "Malakoff",
    "emoji": "🏙️",
    "description": "30 557 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097611,
    "nom": "Mamoudzou",
    "emoji": "🏙️",
    "description": "71 437 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Mayotte",
    "poste": "Mayotte",
    "sigle": "976",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078361,
    "nom": "Mantes-la-Jolie",
    "emoji": "🏙️",
    "description": "43 526 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059378,
    "nom": "Marcq-en-Barœul",
    "emoji": "🏙️",
    "description": "40 184 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013054,
    "nom": "Marignane",
    "emoji": "🏙️",
    "description": "33 692 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013055,
    "nom": "Marseille",
    "emoji": "🏙️",
    "description": "886 040 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013056,
    "nom": "Martigues",
    "emoji": "🏙️",
    "description": "48 298 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091377,
    "nom": "Massy",
    "emoji": "🏙️",
    "description": "51 729 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097307,
    "nom": "Matoury",
    "emoji": "🏙️",
    "description": "36 512 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Guyane",
    "poste": "Guyane",
    "sigle": "973",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90077284,
    "nom": "Meaux",
    "emoji": "🏙️",
    "description": "56 905 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-et-Marne",
    "sigle": "77",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90077288,
    "nom": "Melun",
    "emoji": "🏙️",
    "description": "45 995 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-et-Marne",
    "sigle": "77",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90006083,
    "nom": "Menton",
    "emoji": "🏙️",
    "description": "30 604 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Alpes-Maritimes",
    "sigle": "06",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90033281,
    "nom": "Mérignac",
    "emoji": "🏙️",
    "description": "78 090 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Gironde",
    "sigle": "33",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90057463,
    "nom": "Metz",
    "emoji": "🏙️",
    "description": "122 572 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Moselle",
    "sigle": "57",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092048,
    "nom": "Meudon",
    "emoji": "🏙️",
    "description": "46 334 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069282,
    "nom": "Meyzieu",
    "emoji": "🏙️",
    "description": "36 687 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90040192,
    "nom": "Mont-de-Marsan",
    "emoji": "🏙️",
    "description": "31 592 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Landes",
    "sigle": "40",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90082121,
    "nom": "Montauban",
    "emoji": "🏙️",
    "description": "62 945 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Tarn-et-Garonne",
    "sigle": "82",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90026198,
    "nom": "Montélimar",
    "emoji": "🏙️",
    "description": "40 595 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Drôme",
    "sigle": "26",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078423,
    "nom": "Montigny-le-Bretonneux",
    "emoji": "🏙️",
    "description": "32 465 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90003185,
    "nom": "Montluçon",
    "emoji": "🏙️",
    "description": "33 147 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Allier",
    "sigle": "03",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90034172,
    "nom": "Montpellier",
    "emoji": "🏙️",
    "description": "310 240 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Hérault",
    "sigle": "34",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093048,
    "nom": "Montreuil",
    "emoji": "🏙️",
    "description": "111 934 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092049,
    "nom": "Montrouge",
    "emoji": "🏙️",
    "description": "46 324 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90068224,
    "nom": "Mulhouse",
    "emoji": "🏙️",
    "description": "104 978 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Haut-Rhin",
    "sigle": "68",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90054395,
    "nom": "Nancy",
    "emoji": "🏙️",
    "description": "103 671 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Meurthe-et-Moselle",
    "sigle": "54",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092050,
    "nom": "Nanterre",
    "emoji": "🏙️",
    "description": "97 783 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90044109,
    "nom": "Nantes",
    "emoji": "🏙️",
    "description": "327 734 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Loire-Atlantique",
    "sigle": "44",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90011262,
    "nom": "Narbonne",
    "emoji": "🏙️",
    "description": "57 587 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Aude",
    "sigle": "11",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093050,
    "nom": "Neuilly-sur-Marne",
    "emoji": "🏙️",
    "description": "39 800 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092051,
    "nom": "Neuilly-sur-Seine",
    "emoji": "🏙️",
    "description": "59 538 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90058194,
    "nom": "Nevers",
    "emoji": "🏙️",
    "description": "33 085 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Bourgogne-Franche-Comté",
    "poste": "Nièvre",
    "sigle": "58",
    "couleur": "#6b21a8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90006088,
    "nom": "Nice",
    "emoji": "🏙️",
    "description": "357 737 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Alpes-Maritimes",
    "sigle": "06",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90030189,
    "nom": "Nîmes",
    "emoji": "🏙️",
    "description": "151 839 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Gard",
    "sigle": "30",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90079191,
    "nom": "Niort",
    "emoji": "🏙️",
    "description": "59 854 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Deux-Sèvres",
    "sigle": "79",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094052,
    "nom": "Nogent-sur-Marne",
    "emoji": "🏙️",
    "description": "32 455 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093051,
    "nom": "Noisy-le-Grand",
    "emoji": "🏙️",
    "description": "72 978 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093053,
    "nom": "Noisy-le-Sec",
    "emoji": "🏙️",
    "description": "45 510 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90098818,
    "nom": "Nouméa",
    "emoji": "🏙️",
    "description": "85 976 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Nouvelle-Calédonie",
    "poste": "Nouvelle-Calédonie",
    "sigle": "988",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90045234,
    "nom": "Orléans",
    "emoji": "🏙️",
    "description": "116 357 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Centre-Val de Loire",
    "poste": "Loiret",
    "sigle": "45",
    "couleur": "#0f766e",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069149,
    "nom": "Oullins-Pierre-Bénite",
    "emoji": "🏙️",
    "description": "38 168 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091477,
    "nom": "Palaiseau",
    "emoji": "🏙️",
    "description": "37 471 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093055,
    "nom": "Pantin",
    "emoji": "🏙️",
    "description": "61 929 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90075056,
    "nom": "Paris",
    "emoji": "🏙️",
    "description": "2 103 778 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Paris",
    "sigle": "75",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90064445,
    "nom": "Pau",
    "emoji": "🏙️",
    "description": "80 441 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Pyrénées-Atlantiques",
    "sigle": "64",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90066136,
    "nom": "Perpignan",
    "emoji": "🏙️",
    "description": "121 616 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Pyrénées-Orientales",
    "sigle": "66",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90033318,
    "nom": "Pessac",
    "emoji": "🏙️",
    "description": "67 339 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Gironde",
    "sigle": "33",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078490,
    "nom": "Plaisir",
    "emoji": "🏙️",
    "description": "31 811 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078498,
    "nom": "Poissy",
    "emoji": "🏙️",
    "description": "40 983 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90086194,
    "nom": "Poitiers",
    "emoji": "🏙️",
    "description": "89 916 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Vienne",
    "sigle": "86",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90077373,
    "nom": "Pontault-Combault",
    "emoji": "🏙️",
    "description": "39 096 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-et-Marne",
    "sigle": "77",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095500,
    "nom": "Pontoise",
    "emoji": "🏙️",
    "description": "31 970 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092062,
    "nom": "Puteaux",
    "emoji": "🏙️",
    "description": "44 002 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90029232,
    "nom": "Quimper",
    "emoji": "🏙️",
    "description": "64 385 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Bretagne",
    "poste": "Finistère",
    "sigle": "29",
    "couleur": "#111827",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90051454,
    "nom": "Reims",
    "emoji": "🏙️",
    "description": "177 674 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Marne",
    "sigle": "51",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90035238,
    "nom": "Rennes",
    "emoji": "🏙️",
    "description": "230 890 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Bretagne",
    "poste": "Ille-et-Vilaine",
    "sigle": "35",
    "couleur": "#111827",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90044143,
    "nom": "Rezé",
    "emoji": "🏙️",
    "description": "43 556 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Loire-Atlantique",
    "sigle": "44",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069286,
    "nom": "Rillieux-la-Pape",
    "emoji": "🏙️",
    "description": "31 389 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091521,
    "nom": "Ris-Orangis",
    "emoji": "🏙️",
    "description": "31 189 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90042187,
    "nom": "Roanne",
    "emoji": "🏙️",
    "description": "35 409 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Loire",
    "sigle": "42",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093063,
    "nom": "Romainville",
    "emoji": "🏙️",
    "description": "37 152 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90026281,
    "nom": "Romans-sur-Isère",
    "emoji": "🏙️",
    "description": "33 464 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Drôme",
    "sigle": "26",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093064,
    "nom": "Rosny-sous-Bois",
    "emoji": "🏙️",
    "description": "47 180 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059512,
    "nom": "Roubaix",
    "emoji": "🏙️",
    "description": "98 286 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90076540,
    "nom": "Rouen",
    "emoji": "🏙️",
    "description": "117 662 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Normandie",
    "poste": "Seine-Maritime",
    "sigle": "76",
    "couleur": "#991b1b",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092063,
    "nom": "Rueil-Malmaison",
    "emoji": "🏙️",
    "description": "82 874 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097409,
    "nom": "Saint-André",
    "emoji": "🏙️",
    "description": "58 885 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097410,
    "nom": "Saint-Benoît",
    "emoji": "🏙️",
    "description": "38 604 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90022278,
    "nom": "Saint-Brieuc",
    "emoji": "🏙️",
    "description": "44 364 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Bretagne",
    "poste": "Côtes-d'Armor",
    "sigle": "22",
    "couleur": "#111827",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90042207,
    "nom": "Saint-Chamond",
    "emoji": "🏙️",
    "description": "35 646 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Loire",
    "sigle": "42",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097411,
    "nom": "Saint-Denis",
    "emoji": "🏙️",
    "description": "155 634 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093066,
    "nom": "Saint-Denis",
    "emoji": "🏙️",
    "description": "149 077 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90042218,
    "nom": "Saint-Étienne",
    "emoji": "🏙️",
    "description": "173 136 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Loire",
    "sigle": "42",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078551,
    "nom": "Saint-Germain-en-Laye",
    "emoji": "🏙️",
    "description": "45 931 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90044162,
    "nom": "Saint-Herblain",
    "emoji": "🏙️",
    "description": "50 973 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Loire-Atlantique",
    "sigle": "44",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097412,
    "nom": "Saint-Joseph",
    "emoji": "🏙️",
    "description": "39 207 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097311,
    "nom": "Saint-Laurent-du-Maroni",
    "emoji": "🏙️",
    "description": "54 429 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Guyane",
    "poste": "Guyane",
    "sigle": "973",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90006123,
    "nom": "Saint-Laurent-du-Var",
    "emoji": "🏙️",
    "description": "32 172 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Alpes-Maritimes",
    "sigle": "06",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097413,
    "nom": "Saint-Leu",
    "emoji": "🏙️",
    "description": "36 163 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097414,
    "nom": "Saint-Louis",
    "emoji": "🏙️",
    "description": "54 941 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90035288,
    "nom": "Saint-Malo",
    "emoji": "🏙️",
    "description": "47 439 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Bretagne",
    "poste": "Ille-et-Vilaine",
    "sigle": "35",
    "couleur": "#111827",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097801,
    "nom": "Saint-Martin",
    "emoji": "🏙️",
    "description": "31 160 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Saint-Martin",
    "poste": "Saint-Martin",
    "sigle": "978",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90038421,
    "nom": "Saint-Martin-d'Hères",
    "emoji": "🏙️",
    "description": "37 695 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Isère",
    "sigle": "38",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094068,
    "nom": "Saint-Maur-des-Fossés",
    "emoji": "🏙️",
    "description": "76 572 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90033449,
    "nom": "Saint-Médard-en-Jalles",
    "emoji": "🏙️",
    "description": "32 910 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Gironde",
    "sigle": "33",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90044184,
    "nom": "Saint-Nazaire",
    "emoji": "🏙️",
    "description": "74 568 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Pays de la Loire",
    "poste": "Loire-Atlantique",
    "sigle": "44",
    "couleur": "#15803d",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093070,
    "nom": "Saint-Ouen-sur-Seine",
    "emoji": "🏙️",
    "description": "53 615 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097415,
    "nom": "Saint-Paul",
    "emoji": "🏙️",
    "description": "108 088 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097416,
    "nom": "Saint-Pierre",
    "emoji": "🏙️",
    "description": "85 038 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069290,
    "nom": "Saint-Priest",
    "emoji": "🏙️",
    "description": "49 229 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90002691,
    "nom": "Saint-Quentin",
    "emoji": "🏙️",
    "description": "52 813 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Aisne",
    "sigle": "02",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90083118,
    "nom": "Saint-Raphaël",
    "emoji": "🏙️",
    "description": "37 113 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Var",
    "sigle": "83",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091549,
    "nom": "Sainte-Geneviève-des-Bois",
    "emoji": "🏙️",
    "description": "35 438 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90097418,
    "nom": "Sainte-Marie",
    "emoji": "🏙️",
    "description": "37 093 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "La Réunion",
    "poste": "La Réunion",
    "sigle": "974",
    "couleur": "#0369a1",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013103,
    "nom": "Salon-de-Provence",
    "emoji": "🏙️",
    "description": "44 194 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095585,
    "nom": "Sarcelles",
    "emoji": "🏙️",
    "description": "59 173 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078586,
    "nom": "Sartrouville",
    "emoji": "🏙️",
    "description": "52 763 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90077445,
    "nom": "Savigny-le-Temple",
    "emoji": "🏙️",
    "description": "31 148 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-et-Marne",
    "sigle": "77",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091589,
    "nom": "Savigny-sur-Orge",
    "emoji": "🏙️",
    "description": "37 601 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90067447,
    "nom": "Schiltigheim",
    "emoji": "🏙️",
    "description": "34 708 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Bas-Rhin",
    "sigle": "67",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90034301,
    "nom": "Sète",
    "emoji": "🏙️",
    "description": "45 337 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Hérault",
    "sigle": "34",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093071,
    "nom": "Sevran",
    "emoji": "🏙️",
    "description": "52 535 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90083129,
    "nom": "Six-Fours-les-Plages",
    "emoji": "🏙️",
    "description": "37 109 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Var",
    "sigle": "83",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093072,
    "nom": "Stains",
    "emoji": "🏙️",
    "description": "41 388 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90067482,
    "nom": "Strasbourg",
    "emoji": "🏙️",
    "description": "293 771 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Bas-Rhin",
    "sigle": "67",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90092073,
    "nom": "Suresnes",
    "emoji": "🏙️",
    "description": "48 956 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Hauts-de-Seine",
    "sigle": "92",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90033522,
    "nom": "Talence",
    "emoji": "🏙️",
    "description": "46 338 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Gironde",
    "sigle": "33",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90065440,
    "nom": "Tarbes",
    "emoji": "🏙️",
    "description": "44 399 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Hautes-Pyrénées",
    "sigle": "65",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094073,
    "nom": "Thiais",
    "emoji": "🏙️",
    "description": "32 918 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90057672,
    "nom": "Thionville",
    "emoji": "🏙️",
    "description": "42 658 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Moselle",
    "sigle": "57",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90074281,
    "nom": "Thonon-les-Bains",
    "emoji": "🏙️",
    "description": "37 928 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Haute-Savoie",
    "sigle": "74",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90083137,
    "nom": "Toulon",
    "emoji": "🏙️",
    "description": "179 116 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Var",
    "sigle": "83",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90031555,
    "nom": "Toulouse",
    "emoji": "🏙️",
    "description": "514 819 habitants",
    "rarete": "ultra_rare",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Haute-Garonne",
    "sigle": "31",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059599,
    "nom": "Tourcoing",
    "emoji": "🏙️",
    "description": "98 772 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90031557,
    "nom": "Tournefeuille",
    "emoji": "🏙️",
    "description": "30 168 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Occitanie",
    "poste": "Haute-Garonne",
    "sigle": "31",
    "couleur": "#c2410c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90037261,
    "nom": "Tours",
    "emoji": "🏙️",
    "description": "139 259 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Centre-Val de Loire",
    "poste": "Indre-et-Loire",
    "sigle": "37",
    "couleur": "#0f766e",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078621,
    "nom": "Trappes",
    "emoji": "🏙️",
    "description": "34 689 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093073,
    "nom": "Tremblay-en-France",
    "emoji": "🏙️",
    "description": "38 348 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90010387,
    "nom": "Troyes",
    "emoji": "🏙️",
    "description": "62 088 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Grand Est",
    "poste": "Aube",
    "sigle": "10",
    "couleur": "#7c2d12",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90026362,
    "nom": "Valence",
    "emoji": "🏙️",
    "description": "64 458 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Drôme",
    "sigle": "26",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059606,
    "nom": "Valenciennes",
    "emoji": "🏙️",
    "description": "43 468 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90056260,
    "nom": "Vannes",
    "emoji": "🏙️",
    "description": "55 790 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Bretagne",
    "poste": "Morbihan",
    "sigle": "56",
    "couleur": "#111827",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069256,
    "nom": "Vaulx-en-Velin",
    "emoji": "🏙️",
    "description": "53 069 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069259,
    "nom": "Vénissieux",
    "emoji": "🏙️",
    "description": "65 502 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90078646,
    "nom": "Versailles",
    "emoji": "🏙️",
    "description": "84 095 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Yvelines",
    "sigle": "78",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90038544,
    "nom": "Vienne",
    "emoji": "🏙️",
    "description": "31 778 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Isère",
    "sigle": "38",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091657,
    "nom": "Vigneux-sur-Seine",
    "emoji": "🏙️",
    "description": "31 466 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069264,
    "nom": "Villefranche-sur-Saône",
    "emoji": "🏙️",
    "description": "36 172 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094076,
    "nom": "Villejuif",
    "emoji": "🏙️",
    "description": "60 183 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90033550,
    "nom": "Villenave-d'Ornon",
    "emoji": "🏙️",
    "description": "42 545 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Nouvelle-Aquitaine",
    "poste": "Gironde",
    "sigle": "33",
    "couleur": "#a16207",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059009,
    "nom": "Villeneuve-d'Ascq",
    "emoji": "🏙️",
    "description": "62 868 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094078,
    "nom": "Villeneuve-Saint-Georges",
    "emoji": "🏙️",
    "description": "36 221 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90093078,
    "nom": "Villepinte",
    "emoji": "🏙️",
    "description": "41 470 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Seine-Saint-Denis",
    "sigle": "93",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90069266,
    "nom": "Villeurbanne",
    "emoji": "🏙️",
    "description": "163 684 habitants",
    "rarete": "epique",
    "visuel": "blason",
    "equipe": "Auvergne-Rhône-Alpes",
    "poste": "Rhône",
    "sigle": "69",
    "couleur": "#b91c1c",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90095680,
    "nom": "Villiers-le-Bel",
    "emoji": "🏙️",
    "description": "30 053 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-d'Oise",
    "sigle": "95",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094079,
    "nom": "Villiers-sur-Marne",
    "emoji": "🏙️",
    "description": "33 162 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094080,
    "nom": "Vincennes",
    "emoji": "🏙️",
    "description": "48 193 habitants",
    "rarete": "peu_commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90091687,
    "nom": "Viry-Châtillon",
    "emoji": "🏙️",
    "description": "30 838 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Essonne",
    "sigle": "91",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90013117,
    "nom": "Vitrolles",
    "emoji": "🏙️",
    "description": "36 758 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Provence-Alpes-Côte d'Azur",
    "poste": "Bouches-du-Rhône",
    "sigle": "13",
    "couleur": "#0e7490",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90094081,
    "nom": "Vitry-sur-Seine",
    "emoji": "🏙️",
    "description": "93 963 habitants",
    "rarete": "rare",
    "visuel": "blason",
    "equipe": "Île-de-France",
    "poste": "Val-de-Marne",
    "sigle": "94",
    "couleur": "#1e3a8a",
    "couleurTexte": "#ffffff"
  },
  {
    "id": 90059650,
    "nom": "Wattrelos",
    "emoji": "🏙️",
    "description": "40 847 habitants",
    "rarete": "commun",
    "visuel": "blason",
    "equipe": "Hauts-de-France",
    "poste": "Nord",
    "sigle": "59",
    "couleur": "#1d4ed8",
    "couleurTexte": "#ffffff"
  }
];
